#!/bin/env bash
# fixnames - Replace spaces in file names with underscores

# set -euo pipefail

for f in $(ls -1 ./*\ *.{JPEG,jpg,JPG,jpg,PNG,png}); do
  echo "$f"
  mv "$f" $(echo "$f" | sed 's/ /_/g')
done
