#!/bin/env bash
# fixnames - Replace spaces in file names with underscores

# set -euo pipefail

while IFS= read -r file; do
  echo "$file"
  mv "$file" "${file// /_}"
done < <(find . -regex '.*\ .*\.*')
