#!/bin/env bash

# Colors
RCOL='\e[0m'
RED='\e[0;31m'
GRE='\e[0;32m'
YEL='\e[1;33m'
BLU='\e[1;34m'

# Check command line
if (( $# < 1 )); then
  echo -e "${RED}Usage: $0 <wallpaper path>${RCOL}" >&2
  echo -e "${RED}Where <wallpaper path> is the path to the wallpapers.${RCOL}" >&2
  exit 1
fi

# Set wallpaper path
export WALLPATH="$1"

# Get the number of files in path
export NUMFILES=$(find $WALLPATH -type f -regex '.*\.\(JPEG\|JPG\|PNG\|SVG\|WEBP\|jpeg\|jpg\|png\|svg\|webp\)' 2>/dev/null | wc -l)

# Bail out if no wallpapers are available
if [[ $NUMFILES == 0 ]]; then
  echo -e "${RED}No wallpapers found in $WALLPATH${RCOL}" >&2
  exit 1
fi

# Get last wallpaper used in this path
if [[ -f "$WALLPATH/.wpno" ]]; then
  export OLDNO=$(cat $WALLPATH/.wpno 2>/dev/null)
  if [[ $OLDNO == "" ]]; then
    export OLDNO=0
  fi
else
  export OLDNO=0
fi

# Get new wallpaper
export NEWNO=$(shuf -i 1-$NUMFILES -n 1 2>/dev/null)
while [ $NEWNO -eq $OLDNO ]; do
  export NEWNO=$(shuf -i 1-$NUMFILES -n 1 2>/dev/null)
done

export PAPER=""
export FILES=$(find $WALLPATH -type f -regex '.*\.\(JPEG\|JPG\|PNG\|SVG\|WEBP\|jpeg\|jpg\|png\|svg\|webp\)' 2>/dev/null)
export ITER=1
for FILE in $FILES; do
  if [ $ITER -eq $NEWNO ]; then
    export PAPER="$FILE"
  fi
  ITER=$(($ITER+1))
done

# If wallpaper filename is blank, bail out
if [[ "$PAPER" == "" ]]; then
  echo -e "${RED}Paper was blank. Something went wrong.${RCOL}" >&2
  echo -e "${RED}WALLPATH: $WALLPATH${RCOL}" >&2
  echo -e "${RED}OLDNO: $OLDNO${RCOL}" >&2
  echo -e "${RED}NEWNO: $NEWNO${RCOL}" >&2
  exit 1
fi

echo $NEWNO > $WALLPATH/.wpno

# Get aspect ratio of chosen image
export WIDTH=$(identify -format "%w" "$PAPER")
export HEIGHT=$(identify -format "%h" "$PAPER")
export RATIO=$(echo "$WIDTH / $HEIGHT" | bc -l)

# If aspect ratio is > 2.1 or less than 1.3, use scaled, else zoom
if [[ $(echo "$RATIO > 2.1" | bc -l) -eq 1 || $(echo "$RATIO < 1.3" | bc -l) -eq 1 ]]; then
  gsettings set org.gnome.desktop.background picture-options 'scaled'
else
  gsettings set org.gnome.desktop.background picture-options 'zoom'
fi
# If square, use stretch or tiling
if [[ $(echo "$WIDTH == $HEIGHT" | bc -l) -eq 1 ]]; then
  if [[ $WIDTH -lt 1920 ]]; then
    gsettings set org.gnome.desktop.background picture-options 'wallpaper'
  else
    gsettings set org.gnome.desktop.background picture-options 'stretch'
  fi
fi

# Find out if using dark mode
export MODE=$(gsettings get org.gnome.desktop.interface color-scheme)

# Set the wallpaper
if [[ "$MODE" == "'prefer-dark'" ]]; then
  gsettings set org.gnome.desktop.background picture-uri-dark file://$PAPER
else
  gsettings set org.gnome.desktop.background picture-uri file://$PAPER
fi

echo -e "${GRE}Wallpaper set to \"$PAPER\"${RCOL}"

