#!/bin/env bash
# set -x
# Colors
creset='\e[0m'
red='\e[0;31m'
green='\e[0;32m'

# Check command line
if (( $# < 1 )); then
  echo -e "${red}Usage: $0 <wallpaper path>${creset}" >&2
  echo -e "${red}Where <wallpaper path> is the path to the wallpapers.${creset}" >&2
  exit 1
fi

# Set wallpaper path
wallpath="$1"

# Get the number of files in path
numfiles=$(find $wallpath -type f -regex '.*\.\(JPEG\|JPG\|PNG\|SVG\|WEBP\|jpeg\|jpg\|png\|svg\|webp\)' 2>/dev/null | wc -l)

# Bail out if no wallpapers are available
if (( numfiles == 0 )); then
  echo -e "${red}No wallpapers found in $wallpath${creset}" >&2
  exit 1
fi

# Get last wallpaper used in this path
if [[ -f "$wallpath/.wpno" ]]; then
  oldno=$(cat ${wallpath}/.wpno 2>/dev/null)
  if [[ $oldno == "" ]]; then
    oldno=0
  fi
else
  oldno=0
fi

# Get new wallpaper
newno="$oldno"
while (( newno == oldno )); do
  newno=$(shuf -i 1-$numfiles -n 1 2>/dev/null)
done

paper=""
iter=1
for file in $(find $wallpath -type f -regex '.*\.\(JPEG\|JPG\|PNG\|SVG\|WEBP\|jpeg\|jpg\|png\|svg\|webp\)' 2>/dev/null); do
  if (( iter == newno )); then
    paper="$file"
  fi
  (( iter++ ))
done

# If wallpaper filename is blank, bail out
if [[ "$paper" == "" ]]; then
  echo -e "${red}paper was blank. Something went wrong.${creset}" >&2
  echo -e "${red}wallpath: $wallpath${creset}" >&2
  echo -e "${red}oldno: $oldno${creset}" >&2
  echo -e "${red}newno: $newno${creset}" >&2
  echo -e "${red}iter: $iter${creset}" >&2
  exit 1
fi

echo "$newno" > "$wallpath"/.wpno

# Get aspect ratio of chosen image
width=$(identify -format "%w" "$paper")
height=$(identify -format "%h" "$paper")
ratio=$(echo "scale=1; $width / $height" | bc -l)

# If aspect ratio is > 2.1 or less than 1.3, use scaled, else zoom
if [[ $(echo "scale=1; $ratio > 2.1" | bc -l) -eq 1 || $(echo "$ratio < 1.3" | bc -l) -eq 1 ]]; then
  gsettings set org.gnome.desktop.background picture-options 'scaled'
  style="scaled"
else
  gsettings set org.gnome.desktop.background picture-options 'zoom'
  style="zoom"
fi
# If square, use stretch or tiling
if [[ $(echo "scale=1; $width == $height" | bc -l) -eq 1 ]]; then
  if (( width < 1920 )); then
    gsettings set org.gnome.desktop.background picture-options 'wallpaper'
    style="wallpaper"
  else
    gsettings set org.gnome.desktop.background picture-options 'stretch'
    style="stretch"
  fi
fi

# Find out if using dark mode
mode=$(gsettings get org.gnome.desktop.interface color-scheme)

# Set the wallpaper
if [[ "$mode" == "'prefer-dark'" ]]; then
  gsettings set org.gnome.desktop.background picture-uri-dark file://$paper
else
  gsettings set org.gnome.desktop.background picture-uri file://$paper
fi

# echo -e "${green}Wallpaper set to \"$paper\"${creset} in $mode mode"
if [[ "$mode" == "'prefer-dark'" ]]; then
  mode="dark"
else
  mode="light"
fi
printf "Wallpaper set to %s in %s mode %s\n" "$paper" "$mode" \
  "$style"

